config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  resource :session, only: [:create, :destroy]
  resource :cart, only: [:edit, :update], controller: 'cart'
  resources :users, only: :index
  resources :products, only: [:index, :show, :update]
  resources :purchases, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :user

  after_save :destroy_if_none

  scope :by_product_id, -> product_id do
    joins(:product).where(products: {id: product_id})
  end

  scope :in_stock, -> do
    joins(:product).where('products.quantity >= items.quantity')
  end

  scope :not_in_stock, -> do
    joins(:product).where.not('products.quantity >= items.quantity')
  end

  private

  def destroy_if_none
    destroy if quantity <= 0
  end
end

app/models/payment/credit_card.rb
class Payment::CreditCard < Method
  def self.confirm
    puts('Credit Card confirmed')
  end
end

app/models/payment/method.rb
class Payment::Method
  def self.confirm
    puts('Default Method confirmed')
  end
end

app/models/payment/method_provider.rb
class Payment::MethodProvider
  DEFAULT_METHOD = Method
  METHODS = {
    credit_card: CreditCard,
    ticket: Ticket
  }
  def self.for(name)
    (METHODS[name] || DEFAULT_METHOD)
  end
end

app/models/payment/ticket.rb
class Payment::Ticket < Payment::Method
  def self.confirm
    puts('Ticket confirmed')
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :auth
  helper_method :current_user

  def auth
    redirect_to users_path if current_user.blank?
  end

  def find_user
    User.find(session[:user_id]) if session[:user_id].present?
  end

  def current_user
    @current_user ||= find_user
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def edit
  end

  def update
    send((params[:op]+'_item').to_sym)
  end

  def delete
  end

  private

  def add_item
    if item_in_cart?
      add_present_item
    else
      add_new_item
    end
  end

  def add_new_item
    item = Item.create(product_id: params[:product_id], quantity: 1)
    current_user.items << item
    item.save
  end

  def add_present_item
    item = current_user.items.by_product_id(params[:product_id]).first
    item.quantity += 1
    item.save
  end

  def remove_item
    if item_in_cart?
      item = current_user.items.by_product_id(params[:product_id]).first
      item.quantity -= 1
      item.save
    end
  end

  def item_in_cart?
    params[:product_id].to_i.in?(user_items_products)
  end

  def user_items_products
    current_user.items.pluck(:product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
  end

  def update
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
    not_in_stock = user_items.not_in_stock
    if not_in_stock.any?
      error_flash(not_in_stock)
      redirect_to edit_cart_path
    end
  end

  def create
    method = Payment::MethodProvider.for(payment_method)
    method.confirm
    clear_cart
    success_flash
    redirect_to :root
  end

  private

  def set_purchase
    total = user_items.inject(0) { |t, i| t+i.quantity*i.product.price }
  end
  
  def user_items
    current_user.items
  end

  def payment_method
    params[:purchase][:payment_method].to_sym
  end

  def payment_name
    params[:purchase][:payment_method].humanize
  end

  def clear_cart
    remove_from_stock
    user_items.destroy_all
  end

  def remove_from_stock
    user_items.map do |item|
      item.product.quantity -= item.quantity
      item.product.save
    end
  end

  def error_flash(not_in_stock)
    not_in_stock = not_in_stock.map { |item| item.product.title }
    flash[:error] = 'The products: '+not_in_stock.join(', ') + '. Are not in stock :('
  end

  def success_flash
    flash[:success] = payment_name+': Your purchase was confirmed :)'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :auth

  def create
    user = User.find(params[:user_id])
    session[:user_id] = user.id
    redirect_to products_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :auth
  
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  def add_item(id)
    link_to '+', cart_path(product_id: id, op: :add), method: :put, remote: true
  end

  def remove_item(id)
    link_to '-', cart_path(product_id: id, op: :remove), method: :put, remote: true
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_product(product)
    tag = product.quantity.zero? ? 'del' : 'span'
    stock = product.quantity.zero? ? '<h4 class="out">OUT OF STOCK</h4>' : "<h4>#{product.quantity} in stock</h4>"
    title = "<h2><#{tag}>#{product.title}</#{tag}></h2>"
    price = "<h4>R$ #{'%.2f' % product.price}</h4>"
    description = "<p><#{tag}>#{product.description}</#{tag}></p>"
    data = title+description+stock+price
    data.html_safe
  end

  def add_to_cart(product)
    options = { remote: true, method: :patch, class: 'add-to-cart' }
    path = cart_path(product_id: product.id, op: :add)
    link_to 'ADD TO CART', path, options unless product.quantity.zero?
  end
end

app/views/cart/_update_quantity.html.erb
<%= javascript_tag do %>
  var minus = document.getElementById('minus'+<%= id %>);
  var plus = document.getElementById('plus'+<%= id %>);

  minus.addEventListener('click', function(){
    var quantity = document.getElementById('quantity'+<%= id %>);
    curr = parseInt(quantity.innerHTML);
    if(curr > 0)
      quantity.innerHTML = curr-1;
  });
  plus.addEventListener('click', function(){
    var quantity = document.getElementById('quantity'+<%= id %>);
    curr = parseInt(quantity.innerHTML);
    quantity.innerHTML = curr+1;
  });
<% end %>

app/views/cart/edit.html.erb
<h1>YOUR CART</h1>
<% if current_user.items.length > 0 %>
  <%= link_to 'Buy', new_purchase_path %>
<% end %>
<ul class="cart-list">
  <% current_user.items.each do |item| %>
    <li>
      <span><%= item.product.title %></span>
      <span class="item-quantity">
        <span id="minus<%= item.id %>"><%= remove_item(item.product.id) %></span>
        <span id="quantity<%= item.id %>"><%= item.quantity %></span>
        <span id="plus<%= item.id %>"><%= add_item(item.product.id) %></span>
      </span>
      <%= render 'update_quantity', id: item.id %>
    </li>
  <% end %>

</ul>

app/views/cart/update.html.erb
<h1>Cart#update</h1>
<p>Find me in app/views/cart/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to 'HOME', root_path %>
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash #{key}" %>
      <% end %>

      <div class="user">
        <h2>Hello, <%= current_user.name %></h2>
        <%= link_to  "YOUR CART", edit_cart_path %> |
        <%= link_to "LOG OUT", session_path, method: :delete %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>CHOOSE ITEMS</h1>
<% @products.each do |product|%>
  <div class="product-brief" id="<%= "product-#{product.id}" %>">
    <%= render_product(product) %>
    <%= add_to_cart(product) %>
  </div>
<% end%>

app/views/purchases/new.html.erb
<h1>Choose Payment Method</h1>
<%= form_tag :purchases do |f| %>
  <% methods = Payment::MethodProvider::METHODS.keys.map { |m| [m.to_s.humanize, m] } %>
  <%= select :purchase, :payment_method, methods %>
  <%= submit_tag 'Confirm Method' %>
<% end %>

app/views/users/index.html.erb
<h1>CHOOSE A USER</h1>
<ul>
<% @users.each do |user| %>
  <li><%= link_to  "#{user.name}", session_path(user_id: user.id), method: :post %></li>
<% end %>
</ul>